config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  resource :bookings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departures, class_name: "Flight", foreign_key: :origin
  has_many :arrivals, class_name: "Flight", foreign_key: :destination
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :passenger
  belongs_to :flight

  accepts_nested_attributes_for :passenger
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport", foreign_key: :origin
  belongs_to :to_airport, class_name: "Airport", foreign_key: :destination
  has_many :bookings
  has_many :passengers, through: :bookings

  validates :takeoff, presence: true

  def takeoff_date_formatted
    takeoff.strftime("%b %d at %l:%M")
  end

  def pretty_duration
    hours, minutes = flight_duration.divmod(60)
    "#{hours} hours #{minutes} minutes"
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @passengers = params[:passenger_count].to_i
    @booking = Booking.new
    @passengers.times { @booking.build_passenger }
  end

  def create
    @flight = Flight.find(params[:flight_id])
    @passenger_name = params.dig(:booking, :passenger_attributes, :name)
    @passenger_email = params.dig(:booking, :passenger_attributes, :email)
    @booking = @flight.bookings.new(booking_passenger_params)
    if @booking.save
      PassengerMailer.with(passenger_name: @passenger_name, passenger_email: @passenger_email, flight_id: @flight.id).ticket_email.deliver_later
      redirect_to root_url, notice: "Check your email for your purchase confirmation."
    else
      render :new
    end
  end


  private

  def booking_passenger_params
    params.require(:booking).permit(:flight, passenger_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.where(flight_params) unless flight_params.empty?
  end

  private

  def flight_params
    params.permit(:origin, :destination, :takeoff)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_form.html.erb
<%= form_with model: @booking, class: "p-3"  do |f| %>
    <%= hidden_field_tag :flight_id, @flight.id %>
    <header class="flex justify-between items-start mb-5">
        <h1 class="text-opacity-90 text-xl font-bold mb-3">Review Your Flight ✈️</h1>
        <%= link_to "Start Over", root_path, class: "px-3 py-1 bg-blue-900 text-white rounded shadow" %>
    </header>
        <table class="border bg-white table-auto w-full mb-3">
            <thead>
                <tr>
                    <% %w(Origin Destination Takeoff Flight\ Duration).each do |heading|  %>
                        <th class="underline text-left px-4 py-2"><%= heading %></th>
                    <% end  %>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="px-4 py-2 text-sm"><%= Airport.find(@flight.origin).code %></td>
                    <td class="px-4 py-2 text-sm"><%= Airport.find(@flight.destination).code %></td>
                    <td class="px-4 py-2 text-sm"><%= @flight.takeoff_date_formatted %></td>
                    <td class="px-4 py-2 text-sm"><%= @flight.pretty_duration %></td>
                </tr>
            </tbody>

        </table>
    <p class="text-sm mb-5">Tickets: <%= @passengers %></p>
    <%= f.fields_for :passenger do |p| %>
        <%= p.label :name, class: "text-gray-800 uppercase font-bold text-sm mb-2" %><br />
        <%= p.text_field :name, class: "border p-2 text-sm mb-3" %><br />
        <%= p.label :email, "Where to send your #{'ticket'.pluralize(params[:passenger_count].to_i)}", class: "text-gray-800 uppercase font-bold text-sm mb-2"  %><br />
        <%= p.email_field :email, { placeholder: "hey@hey.com", class: "border p-2 text-sm" } %><br />
    <% end  %>
    <%= f.submit "Book it!", class: "px-5 py-2 bg-gray-900 text-white rounded shadow mt-6" %>
<% end  %>

app/views/bookings/new.html.erb
<main class="p-3">
    <div class="bg-white rounded w-1/2 m-auto p-1 mt-9 shadow-lg">
        <%= render "form"  %>
    </div>
</main>

app/views/flights/_flight.html.erb
<tr>
    <td class="px-4 py-2 text-sm"><%= Airport.find(flight.origin).code %></td>
    <td class="px-4 py-2 text-sm"><%= Airport.find(flight.destination).code %></td>
    <td class="px-4 py-2 text-sm"><%= flight.takeoff_date_formatted %></td>
    <td class="px-4 py-2 text-sm"><%= flight.pretty_duration %></td>
    <td class="px-4 py-2 text-sm text-center"><%= link_to "Book", new_bookings_path(flight_id: flight.id, passenger_count: params[:passengers]), class: "px-3 py-1 bg-blue-900 text-white rounded shadow"  %></td>
</tr>

app/views/flights/_search.html.erb
<%= form_with url: root_url, method: :get  do |f|  %>
    <section class="mt-5 bg-white w-1/2 p-5 shadow-lg m-auto rounded">
        <div class="flex justify-between">
            <div class="w-5/12">
                <%= f.label :from, class: "text-gray-800 uppercase font-bold text-sm py-2"  %><br />
                <%= f.collection_select :origin, Airport.all, :id, :code, { selected: params[:origin] }, { class: "w-full py-2 px-3 bg-opacity-60 bg-white border-2 rounded" }  %>
            </div>
            <div class="w-5/12">
                <%= f.label :to, class: "text-gray-800 uppercase font-bold text-sm py-2" %><br />
                <%= f.collection_select :destination, Airport.all, :id, :code, { selected: params[:destination] }, { class: "w-full py-2 px-3 bg-opacity-60 bg-white border-2 rounded" }  %>
            </div>
        </div>
        <div class="flex justify-between mt-5 items-end">
            <div class="w-5/12">
                <%= f.label :passengers, class: "text-gray-800 uppercase font-bold text-sm pr-4 py-2"  %><br />
                <%= f.select :passengers, (1..4).to_a, { selected: params[:passengers] }, {  class: "w-full py-2 px-3 border-2 rounded bg-white" }  %>
            </div>
            <div class="w-5/12">
                <%= f.label :departing, class: "text-gray-800 uppercase font-bold text-sm pr-4 py-2"  %>
                <%= date_field_tag :takeoff, nil, class: "w-full py-2 px-3 rounded border-2"  %>
            </div>
        </div>
        <div class="text-right">
            <%= f.submit "Search", class: "px-5 py-2 bg-gray-900 text-white rounded shadow mt-6" %>
        </div>
    </section>
<% end  %>

app/views/flights/index.html.erb
<header class="flex justify-center mt-8 text-lg font-bold">
    <h1><%= link_to "ONE WAY FLIGHTS", root_url, class: "text-white text-opacity-90 text-2xl"  %></h1>
</header>
<main class="p-3">
    <%= render "search" %>
    <% if @flights && @flights.count > 0  %>
        <div class="bg-white rounded w-1/2 m-auto p-1 mt-9 shadow-lg">
            <% if @flights.count > 0 %>
                <table class="border bg-white table-auto w-full">
                    <tr>
                        <thead>
                            <tr>
                                <% %w(Origin Destination Takeoff Flight\ Duration).each do |heading|  %>
                                    <th class="underline text-left px-4 py-2"><%= heading %></th>
                                <% end  %>
                            </tr>
                        </thead>
                    </tr>
                    <tbody>
                        <%= render @flights %>
                    </tbody>
                </table>
            <% else  %>
                <p class="px-2 py-1 text-sm">No flights found on the requested date.</p>
            <% end  %>
        </div>
    <% end %>
</main>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div class="py-2 px-3 bg-green-600 text-white">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-gradient-to-b from-gray-800 to-blue-900 h-screen">
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>